### ISSUE TITLE
Detection Button frame issue when using custom font

### ISSUE THREAD

**Issue by Ankish** [psharanda/Atributika#48] opened 2018-08-28 06:35 UTC
I have integrated this in tableview cells with automatic layout. Text is displayed properly, however button frame for touch detection appears to be incorrect. PFA the log and the xcode view debugger image. You can check 3 butons frame's. Frame for the 5 points is completely off the track.

<img width="516" alt="button issue" src="https://user-images.githubusercontent.com/5313847/44704839-7518d200-aaba-11e8-8d7d-2daecd97dce1.png">

[points1.txt](https://github.com/psharanda/Atributika/files/2326827/points1.txt)

**Comment by psharanda** [comment] 2018-08-28 06:53
Hi, please provide test project with this issue reproducible

**Comment by Ankish** [comment] 2018-08-28 10:13
@psharanda : Please checkout this repo https://github.com/Ankish/AttributikaTest .
Few of the links detection button is proper, few detection buttons take larger heights and increases cell height, few button's frames is completely off the track , few merge with other links. PFA image debugger image for the repo uploaded. Thanks for the quick responses, I really appreciate the work.
<img width="542" alt="attributike" src="https://user-images.githubusercontent.com/5313847/44716863-13b42b80-aad9-11e8-9631-5070b96fb606.png">

**Comment by psharanda** [comment] 2018-08-28 10:47
Thanks. This helped a lot. Basically the problem is related to 🔺 emoji. Without it, label works fine. Will post more updates as find more.

**Comment by psharanda** [comment] 2018-08-28 10:57
Ah no, it is not only related to emoji. Real reason is your custom font. With system font AND emoji it works fine

**Comment by Ankish** [comment] 2018-08-28 11:12
Good Find. I see the problem is only with the emoji and not the font. Removing 🔺 that from the sample text seems to work fine.

**Comment by Ankish** [comment] 2018-08-30 08:27
@psharanda : Any Luck or path with this ?

**Comment by psharanda** [comment] 2018-08-30 08:30
For the moment the only advice is to use standard font or don't use emoji

**Comment by assaadaa** [comment] 2019-01-24 13:37
> Hello @psharanda, great library but I have the same problem when using Arabic characters.

It worked when I used a custom font :p

**Comment by psharanda** [comment] 2019-04-07 14:18
Resolved in 4.8.0

**Closed by psharanda** 2019-04-07 14:18 UTC
Labels: bug
